on:
  push:
    paths:
      - ".github/workflows/rust.yml"
      - "**.rs"
      - "**Cargo.toml"
env:
  RUSTFLAGS: -Dwarnings
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache Rust registry based on toml file
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry/cache/
          key: rust-${{ hashFiles('Cargo.toml') }}
      - uses: mozilla-actions/sccache-action@v0.0.5
      - run: cargo test --workspace
      - run: cargo test --workspace -F=py

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache Rust registry based on toml file
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry/cache/
          key: rust-${{ hashFiles('Cargo.toml') }}
      - uses: mozilla-actions/sccache-action@v0.0.5
      - run: cargo clippy --workspace
      - run: cargo clippy --workspace -F=py

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt -- --check
